DetachHead/basedpyright

.vscode/settings.json, package-lock.json, package.json, packages/pyright-internal/src/tests/testUtils.test.ts, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeEvaluator1.test.ts
=> better test result validator function

packages/pyright-internal/src/pyright.ts
=> change the format of the diagnostic counts to avoid pluralizing because "informations" looks weird

docs/configuration.md, packages/pyright-internal/src/analyzer/packageTypeVerifier.ts, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/backgroundAnalysisBase.ts, packages/pyright-internal/src/backgroundThreadBase.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/server.ts, packages/pyright-internal/src/tests/testUtils.test.ts, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeEvaluator1.test.ts, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json
=> set `typeCheckingMode` to `all` by default

packages/pyright-internal/src/analyzer/deprecatedSymbols.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/deprecated1.py
=> remove `typing.Callable` deprecation since `Callable` is not a collection

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/commands/commands.ts, packages/pyright-internal/src/common/diagnostic.ts, packages/pyright-internal/src/common/workspaceEditUtils.ts, packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/tests/fourslash/importSuggestion.invokeCodeAction.fourslash.ts
=> import action

.github/workflows/mypy_primer_pr.yaml, .github/workflows/mypy_primer_push.yaml, packages/pyright-internal/src/analyzer/importResolver.ts, packages/pyright-internal/src/tests/fourslash/completions.parentFolder.fourslash.ts, packages/pyright-internal/src/tests/importResolver.test.ts
=> remove support for relative imports that are not prefixed with a `.`

.vscode/launch.json, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/duplicateImports2.py
=> fix `reportDuplicateImport` not reporting duplicated aliases and duplicated imports across different `import` statements

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/annotatedVar2.py, packages/pyright-internal/src/tests/samples/annotatedVar4.py, packages/pyright-internal/src/tests/samples/annotatedVar5.py, packages/pyright-internal/src/tests/samples/annotations4.py, packages/pyright-internal/src/tests/samples/duplicateDeclaration1.py, packages/pyright-internal/src/tests/samples/final3.py, packages/pyright-internal/src/tests/samples/genericType3.py, packages/pyright-internal/src/tests/samples/recursiveTypeAlias1.py, packages/pyright-internal/src/tests/typeEvaluator1.test.ts, packages/pyright-internal/src/tests/typeEvaluator3.test.ts, packages/pyright-internal/src/tests/typeEvaluator4.test.ts
receclarations of the same time are always a mistake, even more so than redeclarations of different types (which you may sometimes want to do)
fixes #70
=> fix `reportDeclaration` not reporting multiple redeclarations of the same type

packages/vscode-pyright/src/extension.ts
=> prevent vscode extension from locking the language server executable

docs/installation.md
Added information for loading the `basedpyright` LSP server into Neovim, using `pyright`'s declared API.
=> feat(neovim-setup): Update installation.md

docs/installation.md
As result of [this PR](https://github.com/neovim/nvim-lspconfig/pull/3078) being accepted and merged; now Neovim configuration is more direct.
There is no need to continue using another LSP server's configuration to be loaded into Neovim via `nvim-lspconfig`.
=> Neovim setup (updated)

README.md
minor typo - i assume this word was meant to be "basedpyright" instead of "pyright"?
=> docs: pyright/basedpyright typo in readme

.vscode/extensions.json, README.md, docs/configuration.md, packages/pyright-internal/src/analyzer/sourceFile.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/parser/tokenizer.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/pyrightIgnore2.py, packages/pyright-internal/src/tests/samples/pyrightIgnoreBased.py, packages/pyright-internal/src/tests/samples/typeIgnoreBased.py, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json, pyproject.toml
=> option to enforce error codes in `type:ignore`/`pyright:ignore` comments

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/unknown.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> Fix `Unknown` and `Any` variables being coloured as Unbound

.github/workflows/build_and_release.yml
=> set lerna version back before publishing pypi package to fix version output

.github/workflows/build_and_release.yml, .github/workflows/validation.yml, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/samples/subscript_check.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts, pyproject.toml
=> add error when attempting to subscript `AbstractContextManager` and `AbstractAsyncContextManager` at runtime on python 3.8

docs/configuration.md, packages/pyright-internal/src/common/configOptions.ts
=> fix `reportPrivateLocalImportUsage` not being configurable

packages/vscode-pyright/package.json
=> activate vscode extension if workspace contains a `pyproject.toml`

basedpyright/__main__.py
Thank you for this awesome fork!
I suggest to allow running `basedpyright` as a Python module: `python -m basedpyright`. My motivation is that other popular tools, like `flake8`, `mypy`, and even `basedmypy` support this.
Please let me know what you think.
=> Run as a Python module

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/variables.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> fix normal variables incorrectly getting a `TypeAlias` inlay hint if their type came from a type alias

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/samples/missingSuperBased.py, packages/pyright-internal/src/tests/typeEvaluator2.test.ts
=> fix `reportUnsafeMultipleInheritance` false positives when the class has a base class that does not define an `__init__` or `__init_subclass__`

docs/installation.md
There has been some issues about missing information on configuring Neovim for launching the plugin.
This patch attempts to give more guidance on how to get the LSP running, pointing out on necessary dependencies installed for make it happen.
This helps on comments made on #178 regarding the lack of information to have the plugin working. This closes #369.
=> Improve Neovim installation instructions

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> fix `Any` being coloured as a variable instead of a type

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/never.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> fix `Never` type aliases being coloured as a variable when using the new python 3.12 type alias syntax

packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/tests/config.test.ts, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts
=> fix `typeCheckingMode` not defaulting to `"all"` (was broken by a recent upstream change)

.pre-commit-hooks.yaml, README.md
=> move pre-commit to a separate repo to prevent it from attempting to build the package when the hook gets installed

CONTRIBUTING.md, docs/_sidebar.md, docs/build-debug.md, docs/internals.md, docs/upstream.md
=> Documentation improvements

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/tests/samples/reportAny.py
=> don't report unknown/any errors when casting

docs/index.html
Add dark mode theme to current docsify docs with [docsify-darklight-theme](https://docsify-darklight-theme.boopathikumar.me/#/) and a switcher button
1. Dark 
2. Light
=> docs: add dark mode theme

docs/settings.md, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/tests/languageServer.test.ts, packages/vscode-pyright/package.json
=> change default `diagnosticMode` to `"workspace"` and send an error notification over LSP when an invalid value is set

docs/installation.md
This add installation instructions with [Homebrew](https://brew.sh).
closes #556
Waiting for https://github.com/Homebrew/homebrew-core/pull/180649 to be merged.
=> docs: add hombrew install instructions

docs/settings.md, packages/pyright-internal/src/tests/languageServer.test.ts, packages/vscode-pyright/package.json
`"workspace"` is way too slow on a large project
=> set `diagnosticMode` back to `"openFilesOnly"` by default

based_build/generateAllDocstubs.sh
see https://github.com/AThePeanut4/docify/issues/10
=> fix broken stub docstrings from python 3.8 taking precedence over docstrings from 3.12

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/samples/cast.py
=> fix `reportInvalidCast` false positive when casting to/from `None` and `type`

packages/pyright-internal/src/common/commandLineOptions.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/tests/languageServer.test.ts
=> fix unreachable, unused & deprecated diagnostic severity levels not working when set in the language server config

packages/pyright-internal/src/analyzer/patternMatching.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/patternMatching.test.ts, packages/pyright-internal/src/tests/samples/reportUnnecessaryComparison.py
=> don't report `reportUnnecessaryComparison` when using `assert_never` in an intentionally unreachable case in a match statement

packages/vscode-pyright/package.json
=> make the python vscode extension a dependency of the basedpyright vscode extension as it's required to detect the python interpreter

packages/vscode-pyright/src/extension.ts
workaround for https://github.com/astral-sh/uv/issues/6399
=> fix language server crash in vscode when using pypi package installed by uv

docs/_sidebar.md, docs/installation.md
=> improve cli/lsp installation instructions

pdm.lock, pw, pyproject.toml
Update locked dependencies.
There are 7 updates:
| | Package | From | To |
| --- | --- | --- | --- |
| :arrow_up: | [importlib-metadata](https://pypi.org/project/importlib-metadata) | `8.2.0` | `8.4.0` |
| :arrow_up: | [nodejs-wheel](https://pypi.org/project/nodejs-wheel) | `20.16.0` | `20.17.0` |
| :arrow_up: | [nodejs-wheel-binaries](https://pypi.org/project/nodejs-wheel-binaries) | `20.16.0` | `20.17.0` |
| :arrow_up: | [pylint](https://pypi.org/project/pylint) | `3.2.6` | `3.2.7` |
| :arrow_up: | [ruff](https://pypi.org/project/ruff) | `0.5.6` | `0.6.3` |
| :arrow_up: | [tomlkit](https://pypi.org/project/tomlkit) | `0.13.0` | `0.13.2` |
| :arrow_up: | [zipp](https://pypi.org/project/zipp) | `3.19.2` | `3.20.1` |
*Auto-generated by [PDM update action][1]*
[1]: …
=> Update python dependencies

docs/installation.md
Mirroring the changes to ["Language Server Configurations" wiki](https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#python---basedpyright) for two-way discoverability.
This is just documentation for helix-editor/helix#11121
=> Add Helix configuration to installation.md

packages/pyright-internal/src/common/stringUtils.ts, packages/pyright-internal/src/tests/fourslash/completions.fourslash.ts, packages/pyright-internal/src/tests/stringUtils.test.ts
doesn't allow skipping as many sections of characters in the string matching
When the user types `sleep`, it will no longer give `SimpleNamespace` as a suggestion.
`SimpleNamespace`
`^   ^^   ^ ^`
When the user types `aaaaa`, it will no longer give `AbstractAsyncContextManager` as a suggestion.
And you can see an example changed in the unit tests:
`time.gm` only suggests `time.gmtime` and no longer suggests `time.clock_gettime` or `time.clock_gettime_ns`
added unit tests for the changed function
=> improve fuzzy matching for auto-complete suggestions

packages/pyright-internal/src/analyzer/program.ts, packages/pyright-internal/src/backgroundAnalysisBase.ts, packages/pyright-internal/src/baseline.ts, packages/pyright-internal/src/commands/writeBaseline.ts, packages/pyright-internal/src/common/diagnostic.ts, packages/pyright-internal/src/common/diagnosticSink.ts, packages/pyright-internal/src/languageServerBase.ts
=> fix baseline when running in multithreaded/background analysis mode

.github/workflows/docs.yaml, mkdocs.yml, packages/pyright-internal/src/constants.ts, pdm.lock, pyproject.toml
=> docs versioning

packages/pyright-internal/src/common/collectionUtils.ts, packages/pyright-internal/src/languageService/codeActionProvider.ts
- remove useless call that was resolving more info about each suggestion that wasn't being used, which was making it slower to resolve them all
- sort suggestions by their `sortText` and move exact matches to the top. this seems to be something that completions does automatically, but needs to be done manually for code actions
fixes #587
=> Improve import suggestion code actions by showing more relevant suggestions first

docs/usage/import-resolution.md
see https://github.com/DetachHead/basedpyright/issues/731#issuecomment-2408321083
=> update documentation for editables to clarify that it's talking about build backends rather than frontends

docs/benefits-over-pyright/pylance-features.md
If you know about more existing missing features, it would be great to add them. This will help folks decide whether they should adopt basedpyright over pyright.
Jupyter notebook support is a blocker for us.
=> Add link to pylance issues to pylance features page

docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/implicitAbstractClass.py, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json, pdm_build.py
=> add new `reportImplicitAbstractClass` diagnostic rule

packages/pyright-internal/src/realLanguageServer.ts
fixes #785
really should start looking into #64, cuz this is so messy and error prone
=> fix `typeCheckingMode` still defaulting to `"all"` in the language server when there's no config file

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/variables.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> prevent inlay hints from appearing on enum members

docs/benefits-over-pyright/pylance-features.md
It was the same as the 3rd bullet. I deleted this one rather than the other one because the other one has a smoother phrasing.
=> Remove redundant bullet point

docs/configuration/language-server-settings.md, packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/tests/samples/inlay_hints/generics.py, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts, packages/vscode-pyright/package.json
=> add inlay hints for generics when instantiating classes

packages/pyright-internal/src/languageService/codeActionProvider.ts
=> fix import suggestion code actions not working when no workspace is open

packages/pyright-internal/src/localization/localize.ts
Linux uses locale string `en_US.utf-8` instead `en-us.utf-8`. So I added a statement to convert between them correctly.
=> fix locale parsing on Linux

.vscode/settings.json, packages/pyright-internal/src/analyzer/dataClasses.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.cs.json, packages/pyright-internal/src/localization/package.nls.de.json, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/localization/package.nls.es.json, packages/pyright-internal/src/localization/package.nls.fr.json, packages/pyright-internal/src/localization/package.nls.it.json, packages/pyright-internal/src/localization/package.nls.ja.json, packages/pyright-internal/src/localization/package.nls.ko.json, packages/pyright-internal/src/localization/package.nls.pl.json, packages/pyright-internal/src/localization/package.nls.pt-br.json, packages/pyright-internal/src/localization/package.nls.qps-ploc.json, packages/pyright-internal/src/localization/package.nls.ru.json, packages/pyright-internal/src/localization/package.nls.tr.json, packages/pyright-internal/src/localization/package.nls.zh-cn.json, packages/pyright-internal/src/localization/package.nls.zh-tw.json, packages/pyright-internal/src/tests/completions.test.ts, packages/pyright-internal/src/tests/samples/dataclassTransform3.py, packages/pyright-internal/src/tests/typeEvaluator5.test.ts
=> remove incorrect diagnostic for invalid python identifier in dataclass field aliases and prevent them from appearing in completions

packages/pyright-internal/src/analyzer/renameUsageFinder.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/tests/languageServer.test.ts
=> Fix file rename check running on files that aren't part of the workspace

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/generics.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> fix inlay hints appearing on `super()` calls

packages/pyright-internal/package.json, packages/pyright-internal/src/analyzer/binder.ts, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/analyzer/constructorTransform.ts, packages/pyright-internal/src/analyzer/declaration.ts, packages/pyright-internal/src/analyzer/parameterUtils.ts, packages/pyright-internal/src/analyzer/sourceFile.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeUtils.ts, packages/pyright-internal/src/analyzer/typedDicts.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/languageService/hoverProvider.ts, packages/pyright-internal/src/tests/samples/dataclassTransform3.py, packages/pyright-internal/src/tests/samples/initsubclass1.py, packages/pyright-internal/src/tests/samples/overloadImpl1.py, packages/pyright-internal/src/tests/samples/overloadImpl2.py, packages/pyright-internal/src/tests/samples/partial7.py, packages/pyright-internal/src/tests/samples/solver44.py, packages/pyright-internal/src/tests/samples/typeParams8.py, packages/pyright-internal/src/tests/samples/typedDictClosed5.py, packages/pyright-internal/src/tests/typeEvaluator2.test.ts, packages/pyright-internal/src/tests/typeEvaluator5.test.ts, packages/pyright-internal/src/tests/typeEvaluator6.test.ts, packages/pyright-internal/src/tests/typeEvaluator8.test.ts, packages/pyright/package.json, packages/vscode-pyright/package.json
=> Merge 1.1.388

pyproject.toml
I am currently unable to utilize ``basedpyright`` at my place of work because the (industry-standard) managed system we use to procure external code can not identify the license type.
This change replaces the current license property with the registered classifier for the MIT License, ensuring that it will be parsed properly by managed procurement tools like ours.
* Update license data in ``pyproject.toml``, replacing ``license`` property with ``classifiers``, containing the ``License :: OSI Approved :: MIT License`` classifier, and Python version classifiers from ``3.8``–``3.13``.
=> Update License Info with Well-known OSA MIT License Classifier

.gitignore, pdm_build.py
=> fix crash when project contains a `package.json` with `"type: "module"`

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/imports.py
=> fix unknown imports being incorrectly highlighted as a variable

based_build/localization_helper.py, docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/reportAny.test.ts, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json
=> report explicit usages of `Any`

docs/benefits-over-pyright/improved-generic-narrowing.md, docs/configuration.md, package.json, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/analyzer/patternMatching.ts, packages/pyright-internal/src/analyzer/typeGuards.ts, packages/pyright-internal/src/analyzer/typeUtils.ts, packages/pyright-internal/src/common/collectionUtils.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/tests/collectionUtils.test.ts, packages/pyright-internal/src/tests/samples/typeNarrowingIsinstance13.py, packages/pyright-internal/src/tests/samples/typeNarrowingIsinstance6.py, packages/pyright-internal/src/tests/samples/typeNarrowingUsingBounds.py, packages/pyright-internal/src/tests/samples/typeNarrowingUsingBoundsDisabled.py, packages/pyright-internal/src/tests/typeEvaluator1.test.ts, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts, packages/vscode-pyright/schemas/pyrightconfig.schema.json
- use a generic's bound when narrowing with `isinstance` if it's covariant, `Never` if it's contravariant
- creates a union of all possible combinations if it has constraints
fixes #674
=> improved narrowing of generics

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/samples/codeFlow4.py, packages/pyright-internal/src/tests/samples/metaclass7.py
=> show `Never` instead of `NoReturn` when it's inferred as the return type of a function

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/generics.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> fix incorrect inlay hints for generics where one of the types is a tuple

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/final.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> fix readonly property member access highlighting the entire expression as reaonly instead of just the member name

packages/pyright-internal/src/analyzer/typeGuards.ts, packages/pyright-internal/src/analyzer/typeUtils.ts, packages/pyright-internal/src/tests/samples/typeNarrowingUsingBounds.py, packages/pyright-internal/src/tests/samples/typeNarrowingUsingBoundsDisabled.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts
=> fix `strictGenericNarrowing` causing false positive `reportUnnecessaryIsInstance` errors when narrowing `Callable`

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts, uv.lock
=> fix duplicated semantic token for decorators which caused them to not get highlighted as decorators in neovim

packages/pyright-internal/src/analyzer/program.ts
=> fix typeshed files sometimes being treated as source files which can lead to renames causing edits to be applied to typeshed files

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/samples/reportUnusedFunction_final.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts
=> `reportUnusedFunction` on unused protected methods when the class is decorated with `@final`

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/samples/multipleInheritance.py
=> fix `reportUnsafeMultipleInheritance` false positive in diamond inheritance scenarios, which is safe due to how MRO works

packages/pyright-internal/src/analyzer/typePrinter.ts, packages/pyright-internal/src/tests/typePrinter.test.ts
=> fix paramspecs being printed as `Callable` types in inlay hints

docs/configuration/language-server-settings.md
The docs showing how to setup basedpyright with nvim-lspconfig have a small issue. As per [the official docs](https://github.com/neovim/nvim-lspconfig/blob/41e249e7787ab2ca16160bbc4bb4cfca28542995/doc/lspconfig.txt#L99-L122), the lsp-specific config should be within a `settings` key.
=> docs: add missing `settings` table

.vscode/settings.json, packages/pyright-internal/src/analyzer/analysis.ts, packages/pyright-internal/src/analyzer/backgroundAnalysisProgram.ts, packages/pyright-internal/src/analyzer/program.ts, packages/pyright-internal/src/analyzer/programTypes.ts, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/analyzer/sourceFile.ts, packages/pyright-internal/src/backgroundAnalysisBase.ts, packages/pyright-internal/src/baseline.ts, packages/pyright-internal/src/commands/writeBaseline.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/console.ts, packages/pyright-internal/src/common/serviceProviderExtensions.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/pyright.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/tests/config.test.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts, packages/pyright-internal/src/tests/sourceFile.test.ts
=> handle errors reading & writing the baseline file and report config / baseline errors more reliably

docs/benefits-over-pyright/pypi-package-vscode-pinning.md, docs/installation/command-line-and-language-server.md, packages/pyright/README.md, packages/pyright/package.json
- fixes #586
- fixes #549
- fixes #520
=> officially support installing basedpyright via npm

docs/configuration.md, docs/usage/import-statements.md, package-lock.json, packages/pyright-internal/package.json, packages/pyright-internal/src/analyzer/dataClasses.ts, packages/pyright-internal/src/analyzer/packageTypeVerifier.ts, packages/pyright-internal/src/analyzer/patternMatching.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/analyzer/typeUtils.ts, packages/pyright-internal/src/analyzer/types.ts, packages/pyright-internal/src/common/streamUtils.ts, packages/pyright-internal/src/pyright.ts, packages/pyright-internal/src/tests/samples/dataclass10.py, packages/pyright-internal/src/tests/samples/dataclass17.py, packages/pyright-internal/src/tests/samples/matchUnnecessary1.py, packages/pyright-internal/src/tests/samples/metaclass1.py, packages/pyright-internal/src/tests/samples/tuple19.py, packages/pyright-internal/src/tests/samples/typeNarrowingIsinstance19.py, packages/pyright-internal/src/tests/typeEvaluator1.test.ts, packages/pyright-internal/src/tests/typeEvaluator8.test.ts, packages/pyright/package.json, packages/vscode-pyright/package.json
=> Merge 1.1.391

packages/pyright-internal/src/analyzer/codeFlowEngine.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/withGenericExitType.py
=> fix second generic for  `AbstractContextManager` being ignored when determining whether the context manager can suppress exceptions

packages/pyright-internal/src/analyzer/service.ts
=> fix `File or directory "/<default workspace root>" does not exist` error being reported as a language server notification

docs/benefits-over-pyright/improved-reportUninitializedInstanceVariable.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/samples/uninitializedVariableBased1.py, packages/pyright-internal/src/tests/samples/uninitializedVariableBased2.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts
This is a common and good pattern that `reportUninitializedInstanceVariable` currently fails with.
Often we want a class to have a "reset" method to reset it back to its initial state.
But if we initialize everything in `__init__`, that means we're duplicating code, putting it in both `__init__` and in the `reset` method.
So it's better to just put the initializing code in the `reset` method and `__init__` can call the `reset` method.
```python
class C:
x: int
def __init__(self) -> None:
self.reset()
def reset(self) -> None:
self.x = 3
```
But the current implementation of `reportUninitializedInstanceVariable` doesn't see `x` as initialized.
This is a fix for this problem.
=> eliminate some false positives on `reportUninitializedInstanceVariable`

packages/pyright-internal/src/analyzer/program.ts
as far as i can tell this is an upstream bug that was uncovered by #932
fixes #967
=> fix "files to analyze" notification hanging on typeshed stubs when they aren't actually being analyzed

docs/configuration/language-server-settings.md
Hi, it is my first attempt to commit into opensource. I switched from pyright to basedpyright and encountered with difference of configuration in my custom nvim build.
I know, how changed configuration in nvim lsp, but in topic chats by nvim/pyright and etc. I often see questions about configurations (in particular about customization of specific parameters). 
When I first saw the pyright documentation (I was a newbie in programming), I didn't undestand how to customize nested attributes. 
That's why I've decided append example of nvim lsp config with nested attributes configuration case.
Another argument - see into emacs example, `inlayHints` is specified, let's make the documentation more consistent in terms of examples
=> Nvim LSP example documentation

packages/pyright-internal/src/baseline.ts, packages/pyright-internal/src/pyright.ts
=> report an error instead of crashing when attempting to baseline errors from files that are located outside of the project root

docs/configuration/language-server-settings.md, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/tests/chainedSourceFiles.test.ts, packages/pyright-internal/src/tests/completions.test.ts, packages/pyright-internal/src/tests/fourslash/importSuggestion.invokeCodeAction.autoImportCompletionsDisabled.fourslash.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts
=> fix import suggestion code actions being disabled when `basedpyright.analysis.autoImportCompletions` is disabled

docs/benefits-over-pyright/better-defaults.md, docs/configuration.md, packages/pyright-internal/src/analyzer/binder.ts, packages/pyright-internal/src/analyzer/pythonPathUtils.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/common/configOptions.ts
Basically, this PR adds an `allowedUntypedLibraries` config field which is a list of strings (empty by default). If pyright cannot derive the type of a function, it normally gives an error (`reportUnknownMemberType` or `reportUnknownVariableType`), and if the library the method is implemented in is in this list, it doesn't, for example:
```py
from first import foo
from second import bar
foo("123")   # ok
bar("456")   # error
```
Notes:
- Not documented right now
- maybe it's better to name this `allowedUntypedModules` instead of libraries
- maybe it would be good to allow configuring a list of modules deeper than 1 level (i.e. "`library` is strongly typed but `library.new_submodule` isn't"), although I think this is not necessary due to the uses of this feature (the point is that the rule …
=> Implemented allowedUntypedLibraries config

packages/pyright-internal/src/common/chokidarFileWatcherProvider.ts, packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/common/realFileSystem.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/server.ts
=> fall back to chokidar file watcher if the lsp client doesn't support `capabilities.workspace.didChangeWatchedFiles.dynamicRegistration`

package-lock.json, packages/pyright-internal/package.json, packages/pyright-internal/src/analyzer/enums.ts, packages/pyright-internal/src/analyzer/importResolver.ts, packages/pyright-internal/src/analyzer/importStatementUtils.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/analyzer/typePrinter.ts, packages/pyright-internal/src/analyzer/types.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/autoImporter.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/languageService/inlayHintsProvider.ts, packages/pyright-internal/src/tests/samples/inlay_hints/variables.py, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> double click to insert inlay hints

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/generics.py
=> fix inlay hints incorrectly appearing on pseudo-generic classes

packages/pyright-internal/src/languageServerBase.ts
=> fix language server crash when `diagnosticMode` is `"workspace"` and workspace contains jupyter notebooks that haven't yet been opened

packages/pyright-internal/src/languageServerBase.ts
this went undetected during my testing due to #1073
fixes #1069
=> fix issues when deleting notebook cells

packages/pyright-internal/src/languageServerBase.ts
=> feat: add server info

packages/pyright-internal/src/realLanguageServer.ts
=> fix logging in the language server printing upstream version number instead of the basedpyright version number

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/languageService/completionProviderUtils.ts, packages/pyright-internal/src/tests/chainedSourceFiles.test.ts, packages/pyright-internal/src/tests/completions.test.ts, packages/pyright-internal/src/tests/fourslash/typings/fourslash.d.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts
fixes #1078
doesn't work and i can't figure out why. something to do with `onCompletion` and `onCompletionResolve`. if i add the tag in `onCOmpletion` it works but if i do it in `onCompletionResolve` it doesn't, buit i don't think adding it to `onCompletion` is a good idea because it needs to evaluate the type of all the completion items which would probably be bad for performance
=> add deprecated tag to completions

packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/languageServerBase.ts
Related to https://github.com/DetachHead/basedpyright/issues/1081#issuecomment-2659223968
=> fix: include `DiagnosticTag.Deprecated` for all severity levels of `reportDeprecated`

docs/benefits-over-pyright/language-server-improvements.md, docs/configuration.md
for the changes introduced in #1084
=> update documentation about hints / diagnostic tags

packages/pyright-internal/src/analyzer/binder.ts, packages/pyright-internal/src/analyzer/declaration.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/notebooks.test.ts, packages/pyright-internal/src/tests/samples/ipython_display_import/IPython/display.pyi, packages/pyright-internal/src/tests/samples/ipython_display_import/notebook.ipynb
=> automatically import `IPython.display.display` in notebooks to match runtime and pylance

docs/benefits-over-pyright/language-server-improvements.md, docs/configuration/language-server-settings.md, packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/tests/chainedSourceFiles.test.ts, packages/pyright-internal/src/tests/completions.test.ts, packages/pyright-internal/src/tests/envVarUtils.test.ts, packages/pyright-internal/src/tests/harness/fourslash/testLanguageService.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts, packages/pyright-internal/src/workspaceFactory.ts, packages/vscode-pyright/package.json
=> don't add `@override` decorator on method completions if targeting python <3.12 unless `basedpyright.analysis.useTypingExtensions` is enabled

.github/workflows/build_and_release.yml, .github/workflows/validation.yml, packages/browser-pyright/tsconfig.json, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/analyzer/constructors.ts, packages/pyright-internal/src/analyzer/typeUtils.ts, packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/tests/fourslash/completions.override2.fourslash.ts, packages/pyright-internal/src/tests/importResolver.test.ts, packages/pyright-internal/src/tests/samples/typePrinter1.py, pyproject.toml, tsconfig.json, uv.lock
=> fix `@override` completion text edit being added to `__init_subclass__` and metaclass members

packages/browser-pyright/tsconfig.json, packages/pyright-internal/src/languageService/completionProvider.ts, pyproject.toml, tsconfig.json, uv.lock
=> remove usage of esnext `Set.union` in case people are using older node versions

docs/benefits-over-pyright/better-defaults.md, docs/configuration/command-line.md, mkdocs.yml
=> improve documentation for cli options and mention `failOnWarnings` in the footnote for `--warnings`

packages/vscode-pyright/src/extension.ts
=> attempt to fix crash in vscode extension when space in path to `basedpyright-langserver` executable

packages/pyright-internal/src/server.ts
=> use background analysis in debug mode because there are too many bugs that only occur in background analysis that go undetected when debugging

packages/pyright-internal/src/languageService/completionProvider.ts, packages/pyright-internal/src/tests/completions.test.ts
=> disable deprecated check on completions in cases where it causes the type evaluator to randomly specialize instances incorrectly

docs/benefits-over-pyright/improved-translations.md, docs/configuration/config-files.md
Update the documentation since basedpyright has already supported the unix-like locale specifiers (`xx_XX`).
fixes #1040
=> Update documentation for locale configurations

packages/vscode-pyright/package.json, packages/vscode-pyright/src/extension.ts
The `workspace` diagnosticMode is broken due to the changes introduced in [this commit](https://github.com/DetachHead/basedpyright/commit/bad0c199d44d64b0018e485e4c794846ac04d8ad).
TL;DR: the setting uses the wrong key (`python.analysis` instead of `basedpyright.analysis`) [here](https://github.com/DetachHead/basedpyright/blob/57f2e36bc3a22bc017d614b5374ad6928b3cab0f/packages/vscode-pyright/src/extension.ts#L263).
Less TL;DR: Because of this, we send `undefined` as the diagnostic mode to the language server, which messes up [this condition](https://github.com/DetachHead/basedpyright/blob/57f2e36bc3a22bc017d614b5374ad6928b3cab0f/packages/pyright-internal/src/languageServerBase.ts#L633), and we end up [skipping the workspace analysis](https://github.com/DetachHead/basedpyright/blob/main/pack …
=> Fix workspace diagnosticMode in BasedPyright

packages/vscode-pyright/package.json, packages/vscode-pyright/src/extension.ts
fixes #1147
partially addresses #1165
=> remove dependency on python vscode extension and fix pylance check when the python extension isn't installed

packages/pyright-internal/src/analyzer/importResolver.ts, packages/pyright-internal/src/tests/fourslash/import.pytyped.reportPrivateImportUsageIssue.fourslash.ts
=> fix `reportPrivateImportUsage` behaving differently when run on an individual file if imports in other files effect the cached import results

packages/pyright-internal/src/analyzer/importResolver.ts, packages/pyright-internal/src/tests/completions.test.ts, packages/pyright-internal/src/tests/fourslash/completions.builtinOverride.fourslash.ts, packages/pyright-internal/src/tests/fourslash/completions.dictionary.keys.stringLiterals.fourslash.ts, packages/pyright-internal/src/tests/fourslash/shadowedImports.fourslash.ts
close #1172 
don't ignore `/__init__.pyi` files in the cache walk
=> add support for caching stdlib packages

packages/pyright-internal/src/analyzer/importResolver.ts
amendment to #1173 
we shouldn't add private stdlib packages when building the stdlib cache
I think in practice the only private package in the typeshed stdlib is `_typeshed/__init__.pyi`, but it probably makes sense to preserve the "don't cache private modules" for packages too.
=> Don't cache private stdlib packages

docs/configuration/config-files.md, docs/configuration/language-server-settings.md, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/common/commandLineOptions.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/analyzerServiceExecutor.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/tests/config.test.ts, packages/pyright-internal/src/tests/envVarUtils.test.ts, packages/pyright-internal/src/tests/harness/fourslash/testLanguageService.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts, packages/pyright-internal/src/workspaceFactory.ts, packages/vscode-pyright/package.json
This PR introduces a configuration,
* `basedpyright.analysis.fileEnumerationTimeout`: Controls when to show a "slow enumeration" warning (in seconds). Default is 10 seconds. Setting to 0 disables the warning completely.
This setting is only applicable to the VS Code extension and only makes sense to enable it at the language server setting.
* I conducted my testing using extension deveopment host (using provided debugging profile - Pyright extension (watch)
fixes #1168
=> Add configurable file enumeration timeout settings

packages/pyright-internal/src/analyzer/service.ts
When no `pyproject.toml` or `pyrightconfig.json` file exists, the `pythonPath` is not automatically set to `.venv/bin/python` (if applicable). Creating an empty config file allows the autodetection to work again.
The cause is that the existence of a config file is explicitly checked - but a valid project root can be "found" without a config file, if the editor sent the correct workspace folders to the LSP. If the editor doesn't send any workspace folders, then the `projectRoot` is `/<default workspace root>`, which doesn't cause any issues and a venv just won't be detected.
This probably is only a problem outside of VS Code. An easy way to reproduce it is to take any project and just delete the `pyproject.toml` and `pyrightconfig.json` files, then open the project, without first …
=> Allow .venv autodetection when config file missing

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/languageService/semanticTokensProvider.ts, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
Fix #884
For `_getParamSemanticToken`, I adapted [this snippet](https://github.com/DetachHead/basedpyright/blob/0e751de8183ed305969274abaa323e4c75a2cd38/packages/pyright-internal/src/analyzer/packageTypeVerifier.ts#L1005-L1013) for detecting these special parameters in a more general way.
=> Add semantic highlights for `self` and `cls` parameters

packages/vscode-pyright/package.json
fyi @ValdezFOmar i noticed that although both pylance and basedpyright now use the custom `selfParameter` and `clsParameter` semantic token types, the highlighting was still different in vscode:
pylance:
basedpyright:
turns out we can tell vscode to treat these custom semantic token types like `parameter` by default, while still allowing the user to customize them. i'm pretty sure this is what pylance does.
=> configure vscode to treat `selfParameter` and `clsParameter` semantic token types as a subtype of `parameter`

packages/pyright-internal/src/common/configOptions.ts
=> fix "unknown config option" false positive on `reportUnreachable` caused by upstream merge mistake

packages/pyright-internal/src/pyright.ts
`--threads` currently takes in a null value and silently disregards it. This PR rectifies that and throws an error.
fixes #688
=> cli `--threads` should throw error if non integer or 'auto' value is passed

packages/pyright-internal/src/common/workspaceEditUtils.ts, packages/pyright-internal/src/languageService/renameProvider.ts
Neovim currently reports an error that annotations are missing for the edit when trying to rename symbols.
=> fix crash in meovim caused by invalid annotation ID in WorkspaceEdit

packages/pyright-internal/src/realLanguageServer.ts, packages/vscode-pyright/src/extension.ts
=> fix `writeBaseline`, `restartServer` and `createTypeStub` commands only being registered in the vscode extension instead of the language server

packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/tests/fourslash/ignoreComments.invokeCodeAction.fourslash.ts
=> fix `# pyright: ignore` code actions inserting the comment before the last character if the error is on the last line in the file

docs/installation/pre-commit hook.md
Hi, `prefligit` was rename to `prek`, update the docs to reflect that. Ref: https://github.com/j178/prek/releases/tag/v0.0.23
=> Update `prefligit` to `prek` in docs

package-lock.json, packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/method_calls.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
This comes up a lot for me, for example
So I expanded the matching to also hide the inlay hint when the names match, aside from a `self.` prefix.
After doing that, I realized `cls.` deserves similar treatment. But then I took it further and removed the left-side logic so that we hide it if the name matches regardless of the object it's coming from So even if it was `foo.bar.baz.qux`, we still don't show the `qux=` hint.
Also, VSCode automatically organized imports, which seemed harmless but I can revert if undesired.
I wrote a test for both configurations as well as manually verified the behavior:
=> Hide inlay hints when the parameter matches an accessed member's name

packages/pyright-internal/src/languageServerBase.ts
Currently, the server only responds to `onTypeFormatting` requests if clients support dynamic registration for `onTypeFormatting`. However, the server doesn't make use of dynamic registration for this method (or any, except didchangedwatchfiles, I think) capability, so this isn't necessary. We can enable the feature regardless of the client's support for `dynamicRegistration`.
=> fix: enable onTypeFormatting regardless of dynamicRegistration support

packages/pyright-internal/src/analyzer/declarationUtils.ts, packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/languageService/semanticTokensProvider.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/decorators.py, packages/pyright-internal/src/tests/samples/semantic_highlighting/enum.py, packages/pyright-internal/src/tests/samples/semantic_highlighting/final.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
- fixes #1318
- fixes #1391
- fixes #482
- fixes #364
- fixes #262
- fixes #1059
This PR improved semantic tokens and their modifiers in a few ways:
- The modifier `declaration` is used instead of `definition` (consistent with Pylance).
- Enum classes and their members are now represented using the `enum` and `enumMember` token kinds (consistent with Pylance).
- The `property` token kind is used for the name of a property, a magic member access function (e.g. `__getattr__`), and for all member variable accesses (the first and last parts are consistent with Pylance).
- The modifier `static` is applied to static methods.
- Immutable values are detected in more contexts.
The commit messages given some more details, including some small implementation adjustments.
The semantic tokens tests …
=> Improved Semantic Tokens: Enums, Properties, Constants, and Static Methods

.zed/settings.json, docs/installation/ides.md
=> update zed installation instructions to reflect that basedpyright is now the default language server

docs/configuration/config-files.md
=> fix duplicated `reportMatchNotExhaustive` and missing `reportImplicitOverride` in the docs

packages/pyright-internal/src/analyzer/checker.ts
=> quicker way to check if a class is an enum before reporting `reportUnannotatedClassAttribute`

packages/pyright-internal/src/languageService/autoImporter.ts, packages/pyright-internal/src/tests/fourslash/completions.autoimport.reexports.fourslash.ts
fixes #772
We often use this pattern in our monorepo:
Given this structure:
```
components
├── __init__.py
└── foo
├── __init__.py
├── internal
│   ├── __init__.py
│   └── something_internal.py
└── public
├── __init__.py
└── something_public.py
```
We'll implement some symbols (functions, types, etc.) in `internal/something_internal.py`, while re-exporting them in `public/something_public.py`, with the idea that other components will import things from the `public/` folder.
```python
def my_foo_function() -> None:
pass
from components.foo.internal.something_internal import my_foo_function
__all__ = ["my_foo_function"]
from components.foo.public.something_public import my_foo_function  # <== import is from the 'public' part
my_foo_function()
```
One issue with this pattern with …
=> feat(autoImporter): suggest import aliases from user code if explicitly re-exported

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/languageService/semanticTokensProvider.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/class_members.py, packages/pyright-internal/src/tests/samples/semantic_highlighting/final.py, packages/pyright-internal/src/tests/samples/semantic_highlighting/never.py, packages/pyright-internal/src/tests/samples/semantic_highlighting/unknown.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
The main change introduced by this PR is to use the declarations of a given `NameNode` (if basedpyright is able to find any) as the primary source of information when determining semantic tokens instead of using the type of the `NameNode`, while using the type for refining the classification and as a fallback.
This mainly affects variables that store a type, a function, a module, etc.; for example, with the statement `x = lambda i: i + 1`, the type of `x` is a function type while the declaration is a variable declaration.
This change brings the behaviour more in line with Pylance, which appears to follow the following rules for each `NameNode` that is declared as a variable (where earlier rules take precedence over later ones):
1. If the node is declared in a class or the right-hand side …
=> Use declarations as the primary source of semantic tokens

packages/pyright-internal/src/analyzer/typeEvaluator.ts
=> report an error when attempting to subscript `array.array` at runtime on python <3.12
