.vscode/settings.json, README.md, docs/import-resolution.md, docs/settings.md, package.json, packages/pyright-internal/src/commands/commands.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/server.ts, packages/pyright-internal/src/tests/diagnosticOverrides.test.ts, packages/pyright-internal/src/tests/fourslash/fourslash.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.Consts.ts, packages/pyright-internal/src/tests/harness/fourslash/testState.ts, packages/pyright-internal/src/tests/languageServer.test.ts, packages/vscode-pyright/package.json, packages/vscode-pyright/src/extension.ts
=> support enabling the pylance extension while the basedpyright extension is enabled

packages/pyright-internal/src/analyzer/symbolNameUtils.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/inlayHintsProvider.ts, packages/pyright-internal/src/tests/samples/inlay_hints/function_calls.py, packages/pyright-internal/src/tests/samples/inlay_hints/function_defs.py, packages/pyright-internal/src/tests/samples/inlay_hints/variables.py, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts, packages/vscode-pyright/src/extension.ts
- fixes #141
- fixes #136
- fixes #135
- fixes #155
- fixes #138
=> refactor inlay hints

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/variables.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> Fix type alias inlay hints

.github/workflows/build_and_release.yml, README.md, packages/pyright/.gitignore, packages/pyright/README.md, packages/pyright/package.json
fixes #36 
http://basedpyright.com
=> playground

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/languageService/inlayHintsProvider.ts, packages/pyright-internal/src/tests/testUtils.ts, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> fix duplicated inlay hints in neovim

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/languageService/semanticTokensProvider.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/builtin_identifiers.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> Support `defaultLibrary` semantic token modifier

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/decorators.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> Support `decorator` semantic token type

README.md, docs/_sidebar.md, docs/index.html, docs/installation.md
@baco Are these the right links to include for neovim?
fixes #178
=> add links to readme

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/parameters.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> Support `parameter` semantic token type

.github/workflows/validation.yml, pdm_build.py, pyproject.toml
=> Fix `pdm_build` script

README.md, docs/command-line.md, packages/pyright-internal/package-lock.json, packages/pyright-internal/package.json, packages/pyright-internal/src/pyright.ts, pdm_build.py
=> add argument to generate gitlab code quality report

README.md, docs/configuration.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/analyzer/typeEvaluatorTypes.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/samples/cast.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json
=> error on invalid casts

packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/tests/fourslash/importSuggestion.invokeCodeAction.fourslash.ts
=> fix import suggestion code actions being dependent on where the cursor is on the symbol

packages/pyright-internal/src/languageService/codeActionProvider.ts, packages/pyright-internal/src/tests/fourslash/importSuggestion.invokeCodeAction.fourslash.ts, packages/pyright-internal/src/tests/fourslash/importSuggestionWholeModuleImported.invokeCodeAction.fourslash.ts
=> fix suggested import code action not working when the whole module is already imported

README.md
=> Adjust readme for `pyright: ignore[errors]`

packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/multipleInheritance.py
=> fix `reportUnsafeMultipleInheritance` false positives on `TypedDict`s and dataclasses

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/never.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
=> fix values that were narrowed to `Never` being coloured as a type

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/never.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
broken in a92ab39568d95e44d7e1366440a2ff6c71c2480b
fixes #398
=> fix values with a type annotation that were narrowed to `Never` being coloured as a type

pdm.lock, pdm_build.py, pyproject.toml
=> fix pdm build script running npm install and build multiple times

.github/workflows/validation.yml, based_build/generateAllDocstubs.sh, pdm.lock, pyproject.toml
addresses https://github.com/DetachHead/basedpyright/pull/420#issuecomment-2173448497
=> fix python 3.8 docstubs not being generated

docs/configuration.md
I'm integrating basedpyright at work and it took a while to find issue #307, so I added an example to the sample config file of a rule being set for a specific directory.
=> Update configuration.md with scoped rule example

README.md, docs/configuration.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/missingSuperBased_reportUnsafeMultipleInheritance.py, packages/pyright-internal/src/tests/samples/multipleInheritance.py, packages/pyright-internal/src/tests/typeEvaluator2.test.ts
=> fix logic in `reportUnsafeMultipleInheritance` to correctly account for MRO

based_build/generate_docstubs.py, pdm.lock, pdm_build.py, pw, pyproject.toml
Update locked dependencies.
There are 1 updates:
| | Package | From | To |
| --- | --- | --- | --- |
| :arrow_up: | [importlib-metadata](https://pypi.org/project/importlib-metadata) | `7.1.0` | `8.0.0` |
*Auto-generated by [PDM update action][1]*
[1]: https://github.com/pdm-project/update-deps-action
=> Update python dependencies

.vscode/tasks.json, README.md, based_build/generate_docstubs.py, pdm.lock, pyproject.toml
=> docstrings for builtin modules that are partially compiled

README.md, packages/pyright-internal/src/analyzer/renameUsageFinder.ts, packages/pyright-internal/src/analyzer/usageFinder.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/tests/languageServer.test.ts
=> add module/package renaming to the language server

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/samples/typeNarrowingIsClass1.py, packages/pyright-internal/src/tests/typeEvaluator1.test.ts, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts
=> attempt to fix intermittent errors in `if not TYPE_CHECKING` blocks

README.md, docs/configuration.md, packages/pyright-internal/src/common/configOptions.ts, packages/vscode-pyright/schemas/pyrightconfig.schema.json, pyproject.toml
- fixes #496
- fixes #330
- fixes #55
=> disable `enableTypeIgnoreComments` by default

packages/pyright-internal/src/analyzer/typeEvaluator.ts, packages/pyright-internal/src/tests/reportAny.test.ts
=> don't reportAny on the `Any` type istelf

packages/pyright-internal/src/analyzer/analysis.ts, packages/pyright-internal/src/analyzer/backgroundAnalysisProgram.ts, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/backgroundAnalysisBase.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/pyright.ts, packages/pyright-internal/src/tests/config.test.ts, packages/pyright-internal/src/tests/languageServer.test.ts, packages/pyright-internal/src/tests/lsp/languageServerTestUtils.ts
=> language server error notification on invalid config

packages/pyright-internal/src/realLanguageServer.ts
=> don't report "Unhandled method workspace/configuration" error as a notification

based_build/localization_helper.py, pdm.lock, pyproject.toml
To help working on localization, I have made a tool script for comparing localization messages. It provides a TUI to show messages.
Here's how it looks:
I'm not quite sure where it should be put, and maybe this tool is a bit heavy.
=> Add localization helper script

packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/realLanguageServer.ts
- fixes #573 
- fixes #592 (i hope)
=> fix "Unhandled method" crashes in vscode extension

.vscode/settings.json, packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/languageService/inlayHintsProvider.ts, packages/pyright-internal/src/tests/languageServer.test.ts, packages/pyright-internal/src/workspaceFactory.ts
fixes this bug raised by @baco on discord:
fixes #638
=> fix crashes when no workspace is open

packages/pyright-internal/src/constants.ts
=> fix hyperlinks to the docs from diagnostics in the language server

packages/pyright-internal/src/analyzer/typeInlayHintsWalker.ts, packages/pyright-internal/src/tests/samples/inlay_hints/function_calls.py, packages/pyright-internal/src/tests/typeInlayHintsWalker.test.ts
=> No inlay hint for positional arguments

based_build/localization_helper.py, docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/reportUnannotatedClassAttribute.py, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json
=> add new `reportUnannotatedClassAttribute` rule

docs/configuration.md
Removal of parameter duplication and its description.
=> Fix for parameter duplication

docs/installation/ides.md
Add section for installing and configuring basedpyright on Zed IDE.
=> Add installation instructions for Zed IDE.

docs/configuration/language-server-settings.md, docs/installation/ides.md
just moving this to make it consistent with the setup instructions for the other editors.
@JaagupAverin does this look fine to you?
=> move zed langauge server config to the language server config section

docs/installation/command-line-and-language-server.md
fixes #410
@lucascolley is this the correct way to install it? i know nothing about conda
=> add conda install instructions

docs/benefits-over-pyright/language-server-improvements.md, packages/pyright-internal/src/common/chokidarFileWatcherProvider.ts, packages/pyright-internal/src/common/languageServerInterface.ts, packages/pyright-internal/src/common/realFileSystem.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/realLanguageServer.ts, packages/pyright-internal/src/server.ts
=> revert chokidar file watcher fallback for lsp clients that don't support file watching

packages/pyright-internal/src/analyzer/program.ts, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/analyzer/sourceFile.ts, packages/pyright-internal/src/baseline.ts, packages/pyright-internal/src/commands/writeBaseline.ts, packages/pyright-internal/src/languageServerBase.ts
=> fix updating the baseline file when running in pull diagnostics mode

packages/pyright-internal/src/analyzer/binder.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json
=> add suggestion to install stubs package to `reportMissingTypeStubs` for known stubs that aren't in typeshed

packages/pyright-internal/src/analyzer/binder.ts
ref: https://github.com/DetachHead/basedpyright/pull/1158#issuecomment-2746843682
=> add `scipy-stubs` as non-typeshed stub package

packages/pyright-internal/src/baseline.ts
=> fix diagnostics for files that no longer exist being written to the baseline file

packages/pyright-internal/src/pyright.ts
=> fix `--pythonplatform` cli argument accepting invalid values and rejecting valid values

packages/pyright-internal/src/languageService/autoImporter.ts, packages/pyright-internal/src/tests/fourslash/import.publicSymbols.fourslash.ts, packages/pyright-internal/src/tests/fourslash/import.pytyped.dunderAll.fourslash.ts
=> Suggest all non-private variables in autoimport

.basedpyright/baseline.json, docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration/config-files.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/reportIncompatibleUnannotatedOverride.py, packages/pyright-internal/src/tests/samples/reportUnannotatedClassAttribute.py, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json, pyproject.toml
=> add new diagnostic rule `reportIncompatibleUnannotatedOverride` to check unannotated overridden attributes

docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration/config-files.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/common/configOptions.ts, packages/pyright-internal/src/common/diagnosticRules.ts, packages/pyright-internal/src/localization/localize.ts, packages/pyright-internal/src/localization/package.nls.en-us.json, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/reportInvalidAbstractMethod.py, packages/pyright-internal/src/tests/typeEvaluatorBased.test.ts, packages/vscode-pyright/package.json, packages/vscode-pyright/schemas/pyrightconfig.schema.json
=> add new diagnostic rule: `reportInvalidAbstractMethod`

packages/pyright-internal/src/languageService/autoImporter.ts, packages/pyright-internal/src/languageService/inlayHintsProvider.ts
=> fix crash on inlay hints in notebooks when the type comes from another cell

docs/benefits-over-pyright/new-diagnostic-rules.md, docs/configuration/config-files.md, packages/pyright-internal/src/analyzer/checker.ts, packages/pyright-internal/src/tests/checker.test.ts, packages/pyright-internal/src/tests/samples/reportIncompatibleUnannotatedOverride.py
=> fix `reportIncompatibleUnannotatedOverride` false positive & fix case where it changes the behavior of `reportIncompatibleMethodOverride`

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts
- Narrow type for isMethod check
- Deduplicate function and overload type category logic
- Use dedicated functions instead of manually checking flags
- Use `assertNever` in switch-case
=> Refactoring and fixes for `SemanticTokensWalker`

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts, packages/pyright-internal/src/tests/samples/semantic_highlighting/imports.py, packages/pyright-internal/src/tests/semanticTokensProvider.test.ts
Depends on https://github.com/DetachHead/basedpyright/pull/1335
=> Fix duplicate semantic tokens on imports, class and function definitions

packages/pyright-internal/src/analyzer/semanticTokensWalker.ts
Just a refactor to skip duplicate tokens for parameters in a similar fashion to #1338
=> Simplify deduplication of semantic tokens for parameter nodes

docs/benefits-over-pyright/pypi-package-vscode-pinning.md, docs/index.md, docs/installation/pre-commit hook.md
=> improve wording in the cards on the docs home page & mention upstream merging

packages/pyright-internal/src/analyzer/renameUsageFinder.ts, packages/pyright-internal/src/tests/languageServer.test.ts
=> fix renaming files when imported with a relative import

packages/pyright-internal/src/analyzer/backgroundAnalysisProgram.ts, packages/pyright-internal/src/analyzer/program.ts, packages/pyright-internal/src/analyzer/service.ts, packages/pyright-internal/src/backgroundAnalysisBase.ts, packages/pyright-internal/src/baseline.ts, packages/pyright-internal/src/commands/writeBaseline.ts, packages/pyright-internal/src/languageServerBase.ts, packages/pyright-internal/src/pyright.ts
=> add back baseline cache

.github/workflows/mypy_primer_pr.yaml, .github/workflows/mypy_primer_push.yaml, docs/benefits-over-pyright/baseline.md, packages/pyright-internal/src/pyright.ts
=> fix `--baselinefile` cli argument and update the docs to reflect that the baseline file functionality is now stable
